language: java
sudo: true # faster builds
install: mvn --version
jdk:
  - oraclejdk8
script:
  - sudo apt-get install -y nodejs npm
  - npm install -g @angular/cli
  - ./mvnw clean package -Dmaven.test.skip
